Repository astonhaycock/RecipeVision, pull requests merged in 2024-07, with the labels that each got.

#9 Express routes
  .gitignore
  Makefile
  dev/client/src/components/ReviewList.vue
  dev/client/src/views/HomeView.vue
  dev/client/src/views/IngredientView.vue
  dev/client/src/views/RegisterView.vue
  dev/old/index copy.ts
  dev/old/index.ts
  dev/old/index_ai2.ts
  dev/old/session.ts
  dev/server/.env
  dev/server/.gitignore
  dev/server/bun.lockb
  dev/server/package.json
  dev/server/src/env.ts
  dev/server/src/index.ts
  dev/server/src/model.ts
Labels: enhancement, core, backend

#14 Fix vue api
  dev/client/src/components/Login.vue
  dev/client/src/components/NavBar.vue
  dev/client/src/components/NavBarSmall.vue
  dev/client/src/components/OpenAiRecipe.vue
  dev/client/src/components/Recipe.vue
  dev/client/src/components/Register.vue
  dev/client/src/router/index.ts
  dev/client/src/views/AuthView.vue
  dev/client/src/views/LoginView.vue
  dev/client/src/views/RegisterView.vue
Labels: bug, enhancement, core, frontend

#16 Updated schema for scalability and practicality.
  dev/server/src/index.ts
  dev/server/src/model.ts
Labels: enhancement, core, backend

#25 Backend modularizations
  dev/old/index copy.ts
  dev/old/index.ts
  dev/old/index_ai2.ts
  dev/old/session.ts
  dev/server/API.pdf
  dev/server/API.typ
  dev/server/bun.lockb
  dev/server/package.json
  dev/server/src/env.ts
  dev/server/src/express/api/auth.ts
  dev/server/src/express/api/ingredients.ts
  dev/server/src/express/api/openai.ts
  dev/server/src/express/middleware.ts
  dev/server/src/express/server.ts
  dev/server/src/express/static.ts
  dev/server/src/index.ts
  dev/server/src/model.ts
  dev/server/src/types/index.d.ts
  dev/server/src/utils.ts
Labels: documentation, enhancement, core, backend
